name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_KEY }}
        CI: true
        NODE_ENV: development
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install node-gyp
    - run: npm rebuild
    - run: npm run build --if-present
    - run: npm test

